<a href="https://colab.research.google.com/github/angelfox4/Pytorch_Introduction/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이토치로 로지스틱 회귀 구현하기

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
torch.manual_seed(1)

In [ ]:
x_data=[[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [ ]:
W=torch.zeros((2,1),requires_grad=True)
b=torch.zeros(1, requires_grad=True)

시그모이드 구현

In [ ]:
#가설식(시그모이드)
hypothesis=1/(1+torch.exp(-(x_train.matmul(W)+b)))

In [ ]:
#PyTorch에서 제공하는 함수
hypothesis=torch.sigmoid(x_train.matmul(W)+b) ##nn.sigmoid도 가능한 듯

크로스 엔트로피 구현

In [ ]:
#총 6개의 원소가 존재하지만 하나의 샘플. 즉, 하나의 원소에 대해서만 오차를 구하는 식
-(y_train[0] * torch.log(hypothesis[0]) + 
  (1 - y_train[0]) * torch.log(1 - hypothesis[0]))

tensor([0.6931], grad_fn=<NegBackward>)

In [ ]:
# 모든 원소에 대해서 오차
losses=-(y_train*torch.log(hypothesis)+(1-y_train)*torch.log(1-hypothesis))
cost=losses.mean()
print(cost)

tensor(0.6931, grad_fn=<MeanBackward0>)


In [ ]:
#PyTorch에서 제공하는 함수
F.binary_cross_entropy(hypothesis, y_train) #(예측값, 참값)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

모델의 훈련과정

In [ ]:
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean()

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


In [ ]:
#훈련된 W, b를 이용해 예측값을 출력
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis)
prediction=hypothesis >=torch.FloatTensor([0.5])
print(prediction)

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward>)
tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])


In [ ]:
print(W)
print(b)

tensor([[3.2530],
        [1.5179]], requires_grad=True)
tensor([-14.4819], requires_grad=True)
