<a href="https://colab.research.google.com/github/angelfox4/Pytorch_Introduction/blob/main/cross_entropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn.functional as F
torch.manual_seed(1)

## 소프트맥스 맛보기

In [ ]:
z=torch.FloatTensor([1,2,3])
hypothesis=F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [ ]:
hypothesis.sum()

tensor(1.)

## 비용함수 구현하기(low-level)

In [ ]:
z=torch.rand(3,5, requires_grad=True) #3*5 행렬을 만듦
hypothesis=F.softmax(z, dim=1) #sample(행)기준
print(hypothesis)


tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward>)


In [ ]:
#각 샘플에 대해서 임의의 레이블 만들기
y=torch.randint(5, (3,)).long()
print(y)

tensor([3, 2, 3])


In [ ]:
y_one_hot=torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1) #dim=1, y.unsqueeze(1)의 인덱스에 1을 해당하기

tensor([[0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [ ]:
#비용함수
cost=(y_one_hot* -torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.5497, grad_fn=<MeanBackward0>)


## 비용함수 구현하기(high-level)
주의해야 할 것은 F.cross_entropy는 비용함수에 소프트맥스 함수까지 포함하고 있다는 것

In [ ]:
#low level
torch.log(F.softmax(z, dim=1))
#high level(두 개의 함수를 합한 파이토치 함수)
F.log_softmax(z, dim=1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward>)

In [ ]:
#low level 비용함수
(y_one_hot* -torch.log(hypothesis)).sum(dim=1).mean()
#high level 비용함수
F.nll_loss(F.log_softmax(z, dim=1), y)
#high level 비용함수
F.cross_entropy(z, y)

tensor(1.5497, grad_fn=<NllLossBackward>)