<a href="https://colab.research.google.com/github/angelfox4/Pytorch_Introduction/blob/main/LInear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch로 선형회귀 구현
Cost function : MSE  
Optimizer : Gradient descent

1.기본 셋팅

In [ ]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

2. 변수 선언

In [ ]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor(([2],[4],[6]))

3. 가중치와 편향의 초기화

In [ ]:
#가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시
W=torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [ ]:
b=torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


4. 가설 세우기

In [ ]:
hypothesis=x_train*W+b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


5. 비용 함수 선언하기

In [ ]:
cost=torch.mean((hypothesis-y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


6. Optimizer 설정

In [ ]:
optimizer=optim.SGD([W,b],lr=0.01)

7. 경사하강법 구현

In [ ]:
nb_epochs = 2000 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad() #gradient(W.grad, b.grad)를 0으로 초기화
    cost.backward() #비용 함수를 미분하여 w, b에 대한 gradient를 계산, w.grad, b.grad가 생성됨
    optimizer.step() #W와 b를 업데이트(w_new=w_old-alpha*w.grad, b_new=b_old-alpha*b.grad)

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 1.997, b: 0.006 Cost: 0.000005
Epoch  100/2000 W: 1.998, b: 0.005 Cost: 0.000003
Epoch  200/2000 W: 1.998, b: 0.004 Cost: 0.000002
Epoch  300/2000 W: 1.999, b: 0.003 Cost: 0.000001
Epoch  400/2000 W: 1.999, b: 0.002 Cost: 0.000001
Epoch  500/2000 W: 1.999, b: 0.002 Cost: 0.000000
Epoch  600/2000 W: 1.999, b: 0.001 Cost: 0.000000
Epoch  700/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch  800/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch  900/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1000/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1100/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1200/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1300/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1400/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1500/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1600/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1700/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1800/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1900/2000 W: 2.000, b: 0.000 Cost: 0.000000


8. optimizer.zero_grad()가 필요한 이유  
파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징이 있기 때문에

In [ ]:
import torch
w=torch.tensor(2.0, requires_grad=True)

nb_epochs=20
for epoch in range(nb_epochs+1):

  z=2*w

  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))


수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0
