<a href="https://colab.research.google.com/github/angelfox4/Pytorch_Introduction/blob/main/nn_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# nn.Module로 구현하는 선형 회귀

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

## nn.Module로 구현하는 단순선형 회귀

In [ ]:
# 데이터, y=2x가 정답
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [ ]:
#모델을 선언 및 초기화, 단순선형회귀이므로 input_dim=1, output_dim=1
#하나의 입력 x에 대해서 하나의 출력 y을 가지므로 입력 차원고 출력 차원 모두 1을 인수로 사용
model=nn.Linear(1,1)

In [ ]:
print(list(model.parameters())) #랜덤 초기값, 자동미분이 되므로 requires_grad=True

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [ ]:
#optimizer 설정, 경사 하강법 SGD를 사용하고, learning rate를 의미하는 lr은 0.01
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

In [ ]:
#PyTorch로 구현
nb_epochs=2000
for epoch in range(nb_epochs+1):

  #H(x) 계산
  prediction=model(x_train)

  #cost 계산
  cost=F.mse_loss(prediction, y_train) #PyTorch에서 제공하는 MSE 함수

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 ==0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))    

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [ ]:
#W, b의 값이 최적화되었는지 확인
new_var=torch.FloatTensor([[4.0]])
pred_y=model(new_var)
print(pred_y) #참값인 8과 비슷하게 나오는 것을 확인할 수 있음

tensor([[7.9989]], grad_fn=<AddmmBackward>)


## nn.Module로 구현하는 다중선형회귀
단순선형회귀와 model의 인자값만 다름

In [ ]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
# 3개의 입력 x에 대해서 하나의 출력 y를 가지므로
model = nn.Linear(3,1)

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [ ]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 42134.707031
Epoch  100/2000 Cost: 5.960053
Epoch  200/2000 Cost: 5.654689
Epoch  300/2000 Cost: 5.365413
Epoch  400/2000 Cost: 5.091413
Epoch  500/2000 Cost: 4.831831
Epoch  600/2000 Cost: 4.585963
Epoch  700/2000 Cost: 4.353061
Epoch  800/2000 Cost: 4.132451
Epoch  900/2000 Cost: 3.923452
Epoch 1000/2000 Cost: 3.725488
Epoch 1100/2000 Cost: 3.537961
Epoch 1200/2000 Cost: 3.360339
Epoch 1300/2000 Cost: 3.192085
Epoch 1400/2000 Cost: 3.032697
Epoch 1500/2000 Cost: 2.881700
Epoch 1600/2000 Cost: 2.738672
Epoch 1700/2000 Cost: 2.603207
Epoch 1800/2000 Cost: 2.474846
Epoch 1900/2000 Cost: 2.353291
Epoch 2000/2000 Cost: 2.238137


In [ ]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)  #참값인 152와 가깝게 나옴

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[153.7184]], grad_fn=<AddmmBackward>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.8541, 0.8475, 0.3096]], requires_grad=True), Parameter containing:
tensor([0.3568], requires_grad=True)]
