<a href="https://colab.research.google.com/github/angelfox4/Pytorch_Introduction/blob/main/Tensor_Manipulation_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 넘파이로 텐서 만들기(벡터와 행렬 만들기)

In [ ]:
import numpy as np

1)1D with Numpy

In [ ]:
t=np.array([0,1,2,3,4,5,6])
print(t)


[0 1 2 3 4 5 6]


In [ ]:
print(t.ndim) #차원
print(t.shape) #크기

1
(7,)


1-1)Numpy로 기초 이해하기


In [ ]:
#Indexing
print(t[0])
print(t[1])
print(t[-1])


0
1
6


In [ ]:
#Slicing
print(t[2:5])
print(t[4:-1])
print(t[:2])
print(t[3:])

[2 3 4]
[4 5]
[0 1]
[3 4 5 6]


## 2D with Numpy

In [ ]:
t=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t)
print(t.ndim)
print(t.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


## PyTorch Tensor Allocation(파이토치 텐서 선언하기)

1)1D with PyTorch

In [ ]:
import torch

In [ ]:
t=torch.FloatTensor([0,1,2,3,4,5,6])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim()) #차원
print(t.shape) #크기
print(t.size()) #쿠가

1
torch.Size([7])
torch.Size([7])


In [ ]:
#Indexing&Slicing
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1])
print(t[:2],t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


2)2D with PyTorch

In [ ]:
t=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t.dim()) #차원
print(t.size()) #크기

2
torch.Size([4, 3])


In [ ]:
print(t[:,1])
print(t[:,1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [ ]:
print(t[:,:-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Broadcasting
자동으로 크기를 맞춰서 연산을 수행하게 만드는 기능

In [ ]:
#덧셈 연산
#vector+vector
m1=torch.FloatTensor([[3,3]]) #벡터처럼 보이지만 행렬임
m2=torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [ ]:
#Vector+scalar
m1=torch.FloatTensor([[1,2]]) #벡터처럼 보이지만 행렬임
m2=torch.FloatTensor([[3]])
print(m1+m2)

tensor([[4., 5.]])


In [ ]:
#2*1 vector + 1*2 vector =>2*2로 만들어서 계산
m1=torch.FloatTensor([[1,2]]) #벡터처럼 보이지만 행렬임
m2=torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


## 자주 사용되는 기능들

1) 행렬 곱셈과 곱셈의 차이(Matrix Multiplication Vs. Multiplication)

In [ ]:
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])
print(m1*m2) #Boradcasting+element wise multiplication
print(m1.mul(m2)) #Matrix multiplication

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


2) 평균(Mean)

In [ ]:
#1차원 벡터
t=torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [ ]:
#2차원 행렬
t=torch.FloatTensor([[1,2],[3,4]])
print(t.mean())
print(t.mean(dim=0)) #열을 기준으로<=>열의 차원을 보존하면서 평균을 구한다.
print(t.mean(dim=1)) #행을 기준으로<=>행의 차원을 보존하면서 평균을 구한다.
print(t.mean(dim=-1)) #행을 기준으로<=>행의 차원을 보존하면서 평균을 구한다.

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


3) 덧셈(Sum)

In [ ]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


4)최대(Max)와 아그맥스(ArgMax)

In [ ]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.max)
print(t.max(dim=0))
print(t.max(dim=0)[0]) #max
print(t.max(dim=0)[1]) #argmax
print(t.max(dim=1))
print(t.max(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
<built-in method max of Tensor object at 0x7f3105d88168>
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([3., 4.])
tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
