<a href="https://colab.research.google.com/github/angelfox4/Pytorch_Introduction/blob/main/Tensor_Manipulation_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 뷰(View)
원소의 수를 유지하면서 텐서의 크기 변경
->view는 기본적으로 변경 전과 변경 후의 테너 안의 원소의 개수가 유지되어야 한다.
->파이토치의 view는 사이지ㅡ가 -1로 설정되면 다른 차원으로부터 해당 값을 유추한다.

In [ ]:
import numpy as np
import torch

In [ ]:
t=np.array([[[0,1,2],
            [3,4,5]],
           [[6,7,8],
            [9,10,11]]])
ft=torch.FloatTensor(t)
print(ft)
print(ft.shape) #|t|=(batch size, width, height) 또는 (batch size, length, dim)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


1) 3차원 텐서에서 2차원 텐서로 변경

In [ ]:
print(ft.view([-1,3])) #4*3의 텐서를 얻게 됨, 2차원으로 변경하면서 batch size를 없앰
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


2)3차원 텐서의 크기 변경

In [ ]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## 스퀴즈(Squueeze)
1인 차원을 제거

In [ ]:
ft=torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])
torch.Size([3])


## 언스퀴즈(Unsqueeze)
특정 위치에 1인 차원을 추가한다.

In [ ]:
ft=torch.Tensor([0,1,2])
print(ft) #(3,)
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape) #(1,3)

tensor([0., 1., 2.])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## 타입 캐스팅(Type Casting)
텐서의 자료형을 변화하는 것

In [ ]:
lt=torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [ ]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [ ]:
bt=torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [ ]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## 연결하기(concatenate)
두 텐서를 연결하는 법  
=>두 텐서를 연결해서 입력으로 사용하는 것은 두 가지의 정보를 모두 사용한다는 의미

In [ ]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## 스택킹(Stacking)
영어로 쌓는다는 의미  
때때로 연결을 하는 것보다 스택킹이 더 편리할 때가 있는데, 이는 스택킹이 많은 연산을 포함하고 있기 때문

In [ ]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
#stack은 많은 연산을 함축함
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## ones_like와 zeros_like : 0으로 채워진 텐서와 1로 채워진 텐서
입력 텐서와 크기를 동일하게 하면서 값을 0/1로 채우기

In [ ]:
x=torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation(덮어쓰기 연산)

In [ ]:
x=torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [ ]:
#"_"를 붙이면 덮어쓰기 연산이 가능
print(x.mul_(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
